version: '3.7'

networks:
  eps_net:
services:  
  cloud-ui:
    image: nexus.epsoftinc.in/cloud-ui:${DOCKER_TAG}
    deploy:
      mode: global
    networks:
      - eps_net
    ports:
      - '9090:80'
