version: '3.8'

networks:
  eps_net:
    external: true
    name: "dev_be_default"
  eps_host:
    external: true
    name: host

services:
  cloud-ui:
    image: ${DOCKER_REGISTRY_URL}/cloud-ui:${DOCKER_TAG}
    deploy:
      replicas: 1
    networks:
      - eps_net
    ports:
      - 9198:80
    logging:
      options:
        tag: "{{.Name}}"