version: '3.8'

networks:
  eps_net:
    external: true
    name: "${DOCKER_ENV}_eps_net"
  eps_host:
    external: true
    name: host

services:
  cloud-ui:
    image: ${DOCKER_REGISTRY_URL}/cloud-ui:${DOCKER_TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.environment == qa
    networks:
      - eps_net
    logging:
      options:
        tag: "{{.Name}}"