export const environment = {
    production: true,
    portfolioSite: 'https://10.11.0.82:9098/ang_pages/startforfree.html',
   apiendpoint: 'https://ezflow.demo.epsoftinc.com/aiotalplatform',
   tokenendpoint: 'https://ezidm.demo.epsoftinc.com',
   proxyTokenendpoint: 'https://ezflow.demo.epsoftinc.com/securitymgr',
   authorizationendpoint: 'https://ezflow.demo.epsoftinc.com/authservices',
   socialAndWorkLogin: 'https://ezbotdevapi.aiotal.in',
   notificationsendpoint: 'https://ezflow.demo.epsoftinc.com/alerts',
   Subscriptionendpoint:'https://ezflow.demo.epsoftinc.com/subscriptions',
   productendpoint: 'https://eziap.demo.epsoftinc.com',
   newproductendpoint: 'https://eziap.demo.epsoftinc.com',
   socialLoginRedirectURL: 'https://ezflow.demo.epsoftinc.com/#/user',
   isSecurityManagerEnabled : false,
   isTwoFactorAuthenticationEnabled: false,
   rpaendpoint:"https://ezflow.demo.epsoftinc.com/wfrpa",
   piendpoint:"https://ezflow.demo.epsoftinc.com/prcintel",
   projectendpoint_url: "https://ezflow.demo.epsoftinc.com/pcs",
   isNewDesignEnabled : true,
   isSubscrptionEnabled : true,
   paymentSuccessURL:"https://ezflow.demo.epsoftinc.com/#/success",
   paymentFailuerURL:"https://ezflow.demo.epsoftinc.com/#/",
   stripeKey:"pk_test_51P0drWCJ3cQHk3CPJR9AeA28nQfYeKOIThMG6OGneyWSbbyQ0r61OHtZqkI2mssJrSRbgXDP1urCMu0GPSLewiZu00Usd94Uob",
   product:"AiAgents"
  };