export const environment = {
    production: true,
    portfolioSite: 'http://10.11.0.82:9098/ang_pages/startforfree.html',
    apiendpoint: 'https://ezflow.qa.epsoftinc.com/aiotalplatform',
    tokenendpoint: 'https://ezidm.qa.epsoftinc.com',
    proxyTokenendpoint: 'https://ezflow.qa.epsoftinc.com/securitymgr',
    authorizationendpoint: 'https://ezflow.qa.epsoftinc.com/authservices',
    socialAndWorkLogin: 'https://ezbotdevapi.aiotal.in',
    notificationsendpoint: 'https://ezflow.qa.epsoftinc.com/alerts',
    Subscriptionendpoint:'https://ezflow.qa.epsoftinc.com/subscriptions',
    productendpoint: 'https://eziap.qa.epsoftinc.com',
    newproductendpoint: 'https://eziap.qa.epsoftinc.com',
    socialLoginRedirectURL: 'https://ezflow.qa.epsoftinc.com/#/user',
    rpaendpoint:"https://ezflow.qa.epsoftinc.com/wfrpa",
    piendpoint:"https://ezflow.qa.epsoftinc.com/prcintel",
    asquareproductendpoint: 'https://ezflowasquare.qa.epsoftinc.com',
    isTwoFactorAuthenticationEnabled: false,
    isSecurityManagerEnabled : false,
    isNewDesignEnabled : true,
   isSubscrptionEnabled : true,
   isNewSignupFlow : true,
   paymentSuccessURL:"https://ezflow.qa.epsoftinc.com/#/success",
   paymentFailuerURL:"https://ezflow.qa.epsoftinc.com/#/fail",
   stripeKey:"pk_test_51MnxmQIGBQXHW84IJAWLNX28SJ2JOgyWYhAfZ5Y8mKQzKOZ7SrfQ1ZNmDEcVRrLT3lJti7Qo5jBBxM5AP6n5xVbQ00b9w1UMfK"
  };