export const environment = {
   production: true,
   portfolioSite: 'https://10.11.0.82:9098/ang_pages/startforfree.html',
   apiendpoint: 'https://ezflow.staging.epsoftinc.com/aiotalplatform',
   tokenendpoint: 'https://ezidm.staging.epsoftinc.com',
   proxyTokenendpoint: 'https://ezflow.staging.epsoftinc.com/securitymgr',
   authorizationendpoint: 'https://ezflow.staging.epsoftinc.com/authservices',
   socialAndWorkLogin: 'https://ezbotdevapi.aiotal.in',
   notificationsendpoint: 'https://ezflow.staging.epsoftinc.com/alerts',
   Subscriptionendpoint:'https://ezflow.staging.epsoftinc.com/subscriptions',
   productendpoint: 'https://eziap.staging.epsoftinc.com',
   newproductendpoint: 'https://eziap.staging.epsoftinc.com',
   socialLoginRedirectURL: 'https://ezflow.staging.epsoftinc.com/#/user',
   isSecurityManagerEnabled : false,
   isTwoFactorAuthenticationEnabled: false,
   rpaendpoint:"https://ezflow.staging.epsoftinc.com/wfrpa",
   piendpoint:"https://ezflow.staging.epsoftinc.com/prcintel",
   asquareproductendpoint: 'https://ezflowasquare.staging.epsoftinc.com',
   isNewDesignEnabled : true,
   isSubscrptionEnabled : false,
   paymentSuccessURL:"https://ezflow.staging.epsoftinc.com/#/success",
   paymentFailuerURL:"https://ezflow.staging.epsoftinc.com/#/fail",
   stripeKey:"pk_test_51P0dsYGtSXyupRk8b6KzrZkX2YsNl0HOLhVeZYrL6S12RR4rZd9CGa8O7ckFJLh3kZ3foGrmVdkewcq8cyYTVecj00dG5Dqo2P"
}