export const environment = {
  production: true,
  portfolioSite: 'https://10.11.0.82:9098/ang_pages/startforfree.html',
   apiendpoint: 'https://ezflow.epsoftinc.com/aiotalplatform',
   tokenendpoint: 'https://ezflow.idm.epsoftinc.com',
   proxyTokenendpoint: 'https://ezflow.epsoftinc.com/securitymgr',
   authorizationendpoint: 'https://ezflow.epsoftinc.com/authservices',
   socialAndWorkLogin: 'https://ezbotdevapi.aiotal.in',
   notificationsendpoint: 'https://ezflow.epsoftinc.com/alerts',
   Subscriptionendpoint:'https://ezflow.epsoftinc.com/subscriptions',
   productendpoint: 'https://ezflow.iap.epsoftinc.com',
   newproductendpoint: 'https://ezflow.iap.epsoftinc.com',
   socialLoginRedirectURL: 'https://ezflow.epsoftinc.com/#/user',
   isSecurityManagerEnabled : false,
   isTwoFactorAuthenticationEnabled: false,
   rpaendpoint:"https://ezflow.epsoftinc.com/wfrpa",
   piendpoint:"https://ezflow.epsoftinc.com/prcintel",
   isNewDesignEnabled : true,
   isSubscrptionEnabled : true,
   paymentSuccessURL:"https://ezflow.epsoftinc.com/#/success",
   paymentFailuerURL:"https://ezflow.epsoftinc.com/#/subscription",
   stripeKey:"pk_test_51P0dtDEOiwtmEOoZ8Gxk01D1Lk5WhvdU6YgegYEiUHrmjLqfGLouxVbhwYgjWDylLK8kZ7LLaiDeKqKs15DAfIpB00KPmGpaAo",
   product:"AiAgents"
};
