export const environment = {
    production: true,
    portfolioSite: 'http://10.11.0.82:9098/ang_pages/startforfree.html',
    apiendpoint: 'http://aiotalplatform.qa.epsoftinc.in',
    tokenendpoint: 'http://idm.qa.epsoftinc.in',
    proxyTokenendpoint: 'http://ezflow.qa.epsoftinc.com/securitymgr',
    authorizationendpoint: 'http://authservices.qa.epsoftinc.in',
    socialAndWorkLogin: 'http://ezbotdevapi.aiotal.in',
    notificationsendpoint: 'http://alerts.qa.epsoftinc.in',
    Subscriptionendpoint:'http://subscription.qa.epsoftinc.in',
    productendpoint: 'http://eziap.qa.epsoftinc.in',
    newproductendpoint: 'http://eziap.qa.epsoftinc.in',
    socialLoginRedirectURL: 'http://ezflow.qa.epsoftinc.in/#/user',
    rpaendpoint:"http://rpa.qa.epsoftinc.in",
    piendpoint:"http://pi.qa.epsoftinc.in",
    isTwoFactorAuthenticationEnabled: false,
    isSecurityManagerEnabled : false,
    isNewDesignEnabled : true,
   isSubscrptionEnabled : true,
   paymentSuccessURL:"http://epsoft.internalqa.ai/#/success",
   paymentFailuerURL:"http://epsoft.internalqa.ai/#/",
   stripeKey:"pk_test_51MnxmQIGBQXHW84IJAWLNX28SJ2JOgyWYhAfZ5Y8mKQzKOZ7SrfQ1ZNmDEcVRrLT3lJti7Qo5jBBxM5AP6n5xVbQ00b9w1UMfK",
   product:"AiAgents"
  };